name: perf-pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - numpy=1.18.4
  - pandas=1.0.4
  - xarray=0.15.1
  - dask=2.9.0
  - distributed=2.17.0
  - gcsfs=0.6.2
  - intake=0.6.0
  - intake-xarray=0.3.1
  - netcdf4=1.5.3
  - zarr=2.4.0
  - jupyter=1.0.0
  - ipykernel=5.3.0
  - dask-gateway==0.7.1
  - dask-jobqueue==0.7.1
