name: perf-pangeo
override-channels:
  - https://artifactory.cnes.fr/artifactory/api/conda/conda
dependencies:
  - python=3.6
  - numpy=1.18.4
  - pandas=1.0.4
  - xarray=0.15.1
  - dask=2.17.2
  - distributed=2.17.0
  - gcsfs=0.6.2
  - intake=0.6.0
  - intake-xarray=0.3.1
  - netcdf4=1.5.3
  - zarr=2.4.0
  - jupyter=1.0.0
  - ipykernel=5.3.0
  - dask-gateway==0.7.1
